language: python
python:
  - "3.6"

sudo: required
dist: trusty

branches:
  only:
    - master
    - dev

install:
  - pip install -r requirements.txt
  - bash ./.texlive-minmal-installer.sh
  - source ./srcfile

script:
  - make html
  - make xelatexpdf

after_success:
  - cp build/latex/Makefile.pdf build/html/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: build/html
  on:
    branch: master
