language: python
python:
  - "3.6"

sudo: required
dist: trusty

branches:
  only:
    - master
    - dev

install:
  # Install Python packages
  - pip install -r requirements.txt
  # Install tinytex (https://github.com/yihui/tinytex)
  - wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh;
  - tlmgr install ctex ms xecjk ulem zhnumber fancyhdr titlesec tabulary varwidth \
        float wrapfig parskip capt-of needspace xcolor enumitem xindy fandol \
        pdftexcmds

script:
  - make html
  - make latexpdf

after_success:
  - cp build/latex/Makefile.pdf build/html/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: build/html
  on:
    branch: master
